version: '3.8'

services:
  web:
    build: .
    command: ["/app/wait-for-it.sh", "db:3306", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "9000:9000"
    depends_on:
      - db
      #- redis
    env_file:
      - .env

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  redis:
#    image: redis:7
#    ports:
#      - "6379:6379"

volumes:
  db_data:
