version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
        db:
          condition: service_healthy
    env_file:
      - .env

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  db_data:
